[build]
target = "x86_64-pc-windows-gnu"

# 合并所有target配置到一个部分
[target.x86_64-pc-windows-gnu]
linker = "gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "linker=U:/git/binwalk/builder/local_env/mingw64/bin/gcc.exe"
]